In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot 
import seaborn as sns

In [11]:
#df-suppliers
df=pd.read_csv("Downloads/inventory_cost_demand_project_csvs/suppliers.csv")

In [12]:
df.columns

Index(['supplier_id', 'supplier_name', 'supplier_category', 'supplier_city',
       'supplier_type'],
      dtype='str')

In [13]:
df.describe()

       supplier_id
count     20.00000
mean      10.50000
std        5.91608
min        1.00000
25%        5.75000
50%       10.50000
75%       15.25000
max       20.00000

In [14]:
df.isnull().sum()

supplier_id          0
supplier_name        0
supplier_category    0
supplier_city        0
supplier_type        0
dtype: int64

In [15]:
#df1 - stores
df1=pd.read_csv("Downloads/inventory_cost_demand_project_csvs/stores.csv")

In [16]:
df1.count()

store_id      35
store_name    35
city          35
region        35
store_type    35
dtype: int64

In [17]:
df1.columns

Index(['store_id', 'store_name', 'city', 'region', 'store_type'], dtype='str')

In [18]:
df1.isnull().sum()

store_id      0
store_name    0
city          0
region        0
store_type    0
dtype: int64

In [19]:
#df2 -sales
df2=pd.read_csv("Downloads/inventory_cost_demand_project_csvs/sales.csv")

In [20]:
df2.columns

Index(['sale_id', 'sale_date', 'store_id', 'product_id', 'quantity_sold',
       'unit_price', 'discount', 'vat', 'revenue'],
      dtype='str')

In [21]:
df2.isnull().sum()

sale_id          0
sale_date        0
store_id         0
product_id       0
quantity_sold    0
unit_price       0
discount         0
vat              0
revenue          0
dtype: int64

In [22]:
#df3-products
df3=pd.read_csv("Downloads/inventory_cost_demand_project_csvs/products.csv")

In [23]:
df3.columns

Index(['product_id', 'product_name', 'category', 'unit', 'unit_cost',
       'selling_price', 'vat_rate', 'supplier_id'],
      dtype='str')

In [24]:
df3.isnull().sum()

product_id       0
product_name     0
category         0
unit             0
unit_cost        0
selling_price    0
vat_rate         0
supplier_id      0
dtype: int64

In [25]:
#df4-production
df4=pd.read_csv("Downloads/inventory_cost_demand_project_csvs/production.csv")

In [26]:
df4.columns

Index(['production_id', 'production_date', 'product_id', 'quantity_produced',
       'raw_material_cost', 'labor_cost', 'machine_cost', 'defective_units'],
      dtype='str')

In [27]:
df4.isnull().sum()

production_id        0
production_date      0
product_id           0
quantity_produced    0
raw_material_cost    0
labor_cost           0
machine_cost         0
defective_units      0
dtype: int64

In [28]:
#df5-inventory 
df5=pd.read_csv("Downloads/inventory_cost_demand_project_csvs/inventory.csv")

In [29]:
df5.columns

Index(['inventory_id', 'inventory_date', 'store_id', 'product_id',
       'opening_stock', 'received_quantity', 'issued_quantity',
       'closing_stock', 'damaged_quantity', 'rework_quantity'],
      dtype='str')

In [30]:
df5.isnull().sum()

inventory_id         0
inventory_date       0
store_id             0
product_id           0
opening_stock        0
received_quantity    0
issued_quantity      0
closing_stock        0
damaged_quantity     0
rework_quantity      0
dtype: int64

In [31]:
(df5.isnull().sum()/len(df5))*100

inventory_id         0.0
inventory_date       0.0
store_id             0.0
product_id           0.0
opening_stock        0.0
received_quantity    0.0
issued_quantity      0.0
closing_stock        0.0
damaged_quantity     0.0
rework_quantity      0.0
dtype: float64

In [32]:
df.dtypes

supplier_id          int64
supplier_name          str
supplier_category      str
supplier_city          str
supplier_type          str
dtype: object

In [33]:
df1.dtypes

store_id      int64
store_name      str
city            str
region          str
store_type      str
dtype: object

In [34]:
df2.dtypes

sale_id            int64
sale_date            str
store_id           int64
product_id         int64
quantity_sold      int64
unit_price       float64
discount         float64
vat              float64
revenue          float64
dtype: object

In [35]:
#df2["sale_date"] = pd.to_numeric(df2["sale_date"], errors="coerce").astype("Int64")

#df2["unit_price"] = pd.to_numeric(df2["unit_price"], errors="coerce").astype("Int64")

#df2["discount"] = pd.to_numeric(df2["discount"], errors="coerce").astype("Int64")

#df2["vat"] = pd.to_numeric(df2["vat"], errors="coerce")

#df2["revenue"] = pd.to_numeric(df2["revenue"], errors="coerce")

In [36]:
df2["sale_date"] = pd.to_datetime(df2["sale_date"])

In [37]:
df2.dtypes

sale_id                   int64
sale_date        datetime64[us]
store_id                  int64
product_id                int64
quantity_sold             int64
unit_price              float64
discount                float64
vat                     float64
revenue                 float64
dtype: object

In [38]:
df3.dtypes

product_id         int64
product_name         str
category             str
unit                 str
unit_cost        float64
selling_price    float64
vat_rate         float64
supplier_id        int64
dtype: object

In [39]:
df3.head(4)

,product_id,product_name,category,unit,unit_cost,selling_price,vat_rate,supplier_id
0,1,Butter,Dairy,Box,38.71,69.99,15.0,16
1,2,Butter 2,Dairy,Box,10.27,19.35,15.0,14
2,3,Butter 3,Dairy,Piece,67.35,89.80,15.0,16
3,4,Butter 4,Dairy,Carton,33.09,61.30,15.0,10

In [40]:
df4.dtypes

production_id          int64
production_date          str
product_id             int64
quantity_produced      int64
raw_material_cost    float64
labor_cost           float64
machine_cost         float64
defective_units        int64
dtype: object

In [41]:
df4["production_date"] = pd.to_datetime(df4["production_date"])

In [42]:
df4.dtypes

production_id                 int64
production_date      datetime64[us]
product_id                    int64
quantity_produced             int64
raw_material_cost           float64
labor_cost                  float64
machine_cost                float64
defective_units               int64
dtype: object

In [43]:
df5.dtypes

inventory_id         int64
inventory_date         str
store_id             int64
product_id           int64
opening_stock        int64
received_quantity    int64
issued_quantity      int64
closing_stock        int64
damaged_quantity     int64
rework_quantity      int64
dtype: object

In [44]:
df5["inventory_date"] = pd.to_datetime(df5["inventory_date"])

In [45]:
df5.dtypes

inventory_id                  int64
inventory_date       datetime64[us]
store_id                      int64
product_id                    int64
opening_stock                 int64
received_quantity             int64
issued_quantity               int64
closing_stock                 int64
damaged_quantity              int64
rework_quantity               int64
dtype: object

In [46]:
#df.info()
#df.isnull().sum()
#df.duplicated().sum()
#df.dtypes
#df.describe()

In [47]:
#df1.info()
#df1.isnull().sum()
#df1.duplicated().sum()
#df1.dtypes
#df1.describe()

In [48]:
#df2.info()
#df2.isnull().sum()
#df2.duplicated().sum()
#df2.dtypes
#df2.describe()

In [49]:
#df3.info()
#df3.isnull().sum()
#df3.duplicated().sum()
#df3.dtypes
#df3.describe()

In [50]:
#df4.info()
#df4.isnull().sum()
#df4.duplicated().sum()
#df4.dtypes
#df4.describe()

In [51]:
#df5.info()
#df5.isnull().sum()
#df5.duplicated().sum()
#df5.dtypes
#df5.describe()

In [52]:
# Negative quantities?
df2[df2['quantity_sold'] < 0]

Empty DataFrame
Columns: [sale_id, sale_date, store_id, product_id, quantity_sold, unit_price, discount, vat, revenue]
Index: []

In [53]:
df.columns

Index(['supplier_id', 'supplier_name', 'supplier_category', 'supplier_city',
       'supplier_type'],
      dtype='str')

In [54]:
df1.columns

Index(['store_id', 'store_name', 'city', 'region', 'store_type'], dtype='str')

In [55]:
df2.columns

Index(['sale_id', 'sale_date', 'store_id', 'product_id', 'quantity_sold',
       'unit_price', 'discount', 'vat', 'revenue'],
      dtype='str')

In [56]:
df3.columns

Index(['product_id', 'product_name', 'category', 'unit', 'unit_cost',
       'selling_price', 'vat_rate', 'supplier_id'],
      dtype='str')

In [57]:
df4.columns

Index(['production_id', 'production_date', 'product_id', 'quantity_produced',
       'raw_material_cost', 'labor_cost', 'machine_cost', 'defective_units'],
      dtype='str')

In [58]:
df5.columns

Index(['inventory_id', 'inventory_date', 'store_id', 'product_id',
       'opening_stock', 'received_quantity', 'issued_quantity',
       'closing_stock', 'damaged_quantity', 'rework_quantity'],
      dtype='str')

In [59]:
# Negative prices?
df2[df2['unit_price'] < 0]

Empty DataFrame
Columns: [sale_id, sale_date, store_id, product_id, quantity_sold, unit_price, discount, vat, revenue]
Index: []

In [60]:
# Duplicate IDs?
df2['sale_id'].duplicated().sum()

np.int64(0)

In [61]:
df['supplier_id'].duplicated().sum()
df1['store_id'].duplicated().sum()
df3['product_id'].duplicated().sum()
df2['sale_id'].duplicated().sum()
df4['production_id'].duplicated().sum()
df5['inventory_id'].duplicated().sum()

np.int64(0)

In [62]:
df2.sales[~sales['product_id']].isin(df3.products['product_id'])

AttributeError: 'DataFrame' object has no attribute 'sales'

In [ ]:
sales.columns

In [ ]:
sales_products = df2['product_id'].unique()

In [ ]:
product_ids = df3['product_id'].unique()

In [ ]:
invalid_ids = [x for x in sales_products if x not in product_ids]

In [ ]:
invalid_ids

In [ ]:
supliers_products = df['supplier_id'].unique()
supliers_ids = df3['supplier_id'].unique()

In [ ]:
invalid_ids_1 = [x for x in supliers_products if x not in supliers_ids]

In [ ]:
invalid_ids_1

In [ ]:
prodtn_products = df4['product_id'].unique()
product_ids= df3['product_id'].unique()
invalid_ids_2= [x for x in prodtn_products if x not in product_ids]

In [ ]:
invalid_ids_2

In [ ]:
invent_products=df5["store_id"].unique()
store_ids=df2["store_id"].unique()
invalid_ids_3= [x for x in invent_products if x not in store_ids]

In [ ]:
invalid_ids_3

In [ ]:
invent_products = df5['product_id'].unique()
product_ids= df3['product_id'].unique()
invalid_ids_4= [x for x in invent_products if x not in product_ids]

In [ ]:
invalid_ids_4

In [ ]:
df2[['quantity_sold', 'unit_price', 'discount', 'vat', 'revenue']].min()

In [ ]:
df4[
    ['quantity_produced',
     'raw_material_cost',
     'labor_cost',
     'machine_cost',
     'defective_units']
].min()

In [ ]:
df4[
    df4['defective_units'] > df4['quantity_produced']
]

In [ ]:
df2['sale_date'].min(), df2['sale_date'].max()

In [ ]:
df4['production_date'].min(), df4['production_date'].max()

In [63]:
#df=suppliers
df.to_csv("suppliers_cleaned.csv", index=False)
#df1=stores
df1.to_csv("stores_cleaned.csv", index=False)
#df2=sales
df2.to_csv("sales_cleaned.csv", index=False)
#df3=products
df3.to_csv("products_cleaned.csv", index=False)
#df4=production
df4.to_csv("production_cleaned.csv", index=False)
#df5=inventory 
df5.to_csv("inventory_cleaned.csv", index=False)

In [65]:
import os

folder = "cleaned_data"

os.makedirs(folder, exist_ok=True)

dataframes = {
    "suppliers": df,
    "stores": df1,
    "sales": df2,
    "products": df3,
    "production":df4,
    "inventory": df5
}

for name, df in dataframes.items():
    df.to_csv(
        os.path.join(folder, f"{name}_cleaned.csv"),
        index=False
    )

print("All cleaned CSV files saved successfully!")

All cleaned CSV files saved successfully!

In [ ]:
df5['inventory_date'].min(), df5['inventory_date'].max()

In [66]:
import os

print(os.getcwd())

C:\Users\nandh

In [67]:
os.listdir("cleaned_data")

['inventory_cleaned.csv',
 'production_cleaned.csv',
 'products_cleaned.csv',
 'sales_cleaned.csv',
 'stores_cleaned.csv',
 'suppliers_cleaned.csv']